import type { ITheme } from '@xterm/xterm'
import type { TerminalProfile } from './settings'

interface TerminalThemeOptions {
  theme: ITheme
  fontSize: number
  fontFamily: string
}

export const TERMINAL_THEMES: Record<TerminalProfile, TerminalThemeOptions> = {
  default: {
    fontSize: 14,
    fontFamily: '"Cascadia Code", "Fira Code", "JetBrains Mono", monospace',
    theme: {
      background: '#09090b',
      foreground: '#e4e4e4',
      cursor: '#e4e4e4',
      selectionBackground: '#ffffff40',
    },
  },
  ghostty: {
    fontSize: 14,
    fontFamily: '"Cascadia Code", "Zed Mono", monospace',
    theme: {
      background: '#0d0d0d',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      selectionBackground: '#364a8266',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
  },
  kitty: {
    fontSize: 14,
    fontFamily: '"JetBrains Mono", "Fira Code", monospace',
    theme: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      cursor: '#f5e0dc',
      selectionBackground: '#45475a',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#f5c2e7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    },
  },
  alacritty: {
    fontSize: 13,
    fontFamily: '"JetBrains Mono", "Fira Code", monospace',
    theme: {
      background: '#1c1c1c',
      foreground: '#eeffff',
      cursor: '#ffcc02',
      selectionBackground: '#546e7a66',
      black: '#000000',
      red: '#f07178',
      green: '#c3e88d',
      yellow: '#ffcb6b',
      blue: '#82aaff',
      magenta: '#c792ea',
      cyan: '#89ddff',
      white: '#ffffff',
      brightBlack: '#546e7a',
      brightRed: '#f07178',
      brightGreen: '#c3e88d',
      brightYellow: '#ffcb6b',
      brightBlue: '#82aaff',
      brightMagenta: '#c792ea',
      brightCyan: '#89ddff',
      brightWhite: '#ffffff',
    },
  },
  putty: {
    fontSize: 14,
    fontFamily: '"Courier New", "Lucida Console", monospace',
    theme: {
      background: '#000000',
      foreground: '#00ff00',
      cursor: '#00ff00',
      selectionBackground: '#00800040',
      black: '#000000',
      red: '#bb0000',
      green: '#00bb00',
      yellow: '#bbbb00',
      blue: '#0000bb',
      magenta: '#bb00bb',
      cyan: '#00bbbb',
      white: '#bbbbbb',
      brightBlack: '#555555',
      brightRed: '#ff5555',
      brightGreen: '#55ff55',
      brightYellow: '#ffff55',
      brightBlue: '#5555ff',
      brightMagenta: '#ff55ff',
      brightCyan: '#55ffff',
      brightWhite: '#ffffff',
    },
  },
}
